= JNI wrappers for SAT solvers

image:https://github.com/Lipen/kotlin-jnisat/workflows/Build/badge.svg["Build",link="https://github.com/Lipen/kotlin-jnisat/actions"]
image:https://github.com/Lipen/kotlin-jnisat/workflows/Build%20(Windows)/badge.svg["Build (Windows)",link="https://github.com/Lipen/kotlin-jnisat/actions"]
image:https://jitpack.io/v/Lipen/kotlin-jnisat.svg["JitPack",link="https://jitpack.io/p/Lipen/kotlin-jnisat"]
image:https://hitsofcode.com/github/Lipen/kotlin-jnisat["Hits-of-Code",link="https://hitsofcode.com/view/github/Lipen/kotlin-jnisat"]

== Installation

[source,kotlin]
.build.gradle.kts
----
repositories {
    maven(url = "https://jitpack.io")
}
dependencies {
    implementation("com.github.Lipen:kotlin-jnisat:${Versions.kotlin_jnisat}")
}
----

== Library usage

[source,kotlin]
----
with(JMiniSat()) {
    val x = newVariable()
    val y = newVariable()
    val z = newVariable()

    println("Encoding exactlyOne({x, y, z})")
    addClause(-x, -y)
    addClause(-x, -z)
    addClause(-y, -z)
    addClause(x, y, z)

    println("nvars = $numberOfVariables, nclauses = $numberOfClauses, nlearnts = $numberOfLearnts")
    println("Solving...")
    check(solve()) { "Unexpected UNSAT" }
    println("x = ${getValue(x)}, y = ${getValue(y)}, z = ${getValue(z)}")
    println("model = ${getModel().drop(1)}")

    println("Solving with assumptions...")
    check(solve(x)); check(getValue(x))
    check(solve(y)); check(getValue(y))
    check(solve(z)); check(getValue(z))
    println("Solving with assumptions: OK")
}
----

== Native libs

In order to use JNI wrappers for MiniSat or Cadical (link:src/main/kotlin/com/github/lipen/jnisat/JMiniSat.kt[JMiniSat] and link:src/main/kotlin/com/github/lipen/jnisat/JCadical.kt[JCadical]), you need two native libraries:

1. Shared (dynamic) library for SAT solver (_e.g._, libminisat.so).

- Getting MiniSat shared library is as easy as cloning the https://github.com/niklasso/minisat[git repo] and executing `make lsh`.
More specific build instructions can be found in link:Dockerfile[].
- Cadical can be built from link:https://github.com/arminbiere/cadical[sources] by executing `./configure && make`, but this does not produce *shared* library, only the static one -- however, this may be easily link:cadical-shared-lib.patch[patched].
Another way is to unpack the static lib (`ar -x libcadical.a`, note: do it in an empty folder) and re-link objects into the shared lib (`g++ -o libcadical.so -shared *.o`).
Again, more specific build instructions can be found in link:Dockerfile[].
- Shared (dynamic) libraries must be placed somewhere, where they can be found by Java at runtime.
On Linux, use `/usr/local/lib` (if it is in `LD_LIBRARY_PATH`) or `/usr/lib`.
On Windows, the only working solution is to place DLLs in the current folder (from where you run the dependent app) -- other locations do not work.

2. Shared (dynamic) library for JNI wrapper (_e.g._, libjminisat.so).
This repo is exactly about getting one of those.

- The simplest way of getting it is by downloading it from https://github.com/Lipen/kotlin-jnisat/releases[GitHub Releases] page.
There are at least two places where JNI wrapper library may be placed -- (1) in a folder specified by the `java.library.path` property at runtime (_e.g._, `java -Djava.library.path=/abs/path/to/shared/lib -jar <...>`), or (2) inside the `lib/<platform><arch>` subdirectory of the resources folder (_e.g._, `src/main/resources/lib/linux64/libjminisat.so`).
- Another way is to build the libraries yourself using the provided link:Makefile[].
Configure it manually to match the locations of installed MiniSat and Cadical sources (`<solver>_INCLUDE_DIR`) and libraries (`<solver>_LIB_DIR`).
By default, it is `/usr/local/include` and `/usr/local/lib`.
When done, simply execute `make headers libs` -- this will generate JNI headers for compiled classes using `javah` and assemble shared libraries in `LIB_DIR=build/lib` folder.
Note that `javah` is only available with JDK8 or less.
Alternatively, you can build libraries using Docker -- simply run `make libs-docker`.
