name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      # Note: jdk8 is necessary to use javah
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Set up build cache
        uses: pat-s/always-upload-cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build project using Gradle
        run: ./gradlew build -x test --stacktrace --scan

      - name: Build MiniSat
        working-directory: jni
        run: |
          git clone --depth=1 https://github.com/msoos/minisat minisat-src
          cd minisat-src
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
          cmake --install build --prefix install
          strip -s install/lib/libminisat.so

      - name: Build Glucose
        working-directory: jni
        run: |
          git clone --depth=1 https://github.com/wadoon/glucose glucose-src
          cd solvers/glucose-src
          git apply -v ../patches/glucose-install.patch
          cmake -B build -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build build -- -j8
          cmake --install build --prefix install
          strip -s install/lib/libglucose.so

      - name: Build Cadical
        working-directory: jni
        run: |
          git clone --depth=1 --branch rel-1.4.1 https://github.com/arminbiere/cadical solvers/cadical-src
          cd solvers/cadical-src
          git apply -v ../../patches/cadical-shared.patch
          patch -p0 < ../../patches/cadical-stats.patch
          ./configure -fPIC
          make -j8 shared
          install -m 644 src/cadical.hpp -Dt install/include/cadical
          install -m 644 build/libcadical.so -Dt install/lib
          strip -s install/lib/libcadical.so

      - name: Build CryptoMiniSat
        working-directory: jni
        run: |
          git clone --depth=1 https://github.com/msoos/cryptominisat cms-src
          cd solvers/cms-src
          cmake -B build -DENABLE_PYTHON_INTERFACE=OFF -DCMAKE_BUILD_TYPE=Release
          cmake --build build -- -j8
          cmake --install build --prefix install
          strip -s install/lib/libcryptominisat5.so

      - name: Set up ld cache
        working-directory: jni
        run: sudo ldconfig $(realpath solvers/*-src/install/lib)

      - name: Build JNI libs
        working-directory: jni
        run: make libs \
          MINISAT_INSTALL_DIR=minisat-src/install \
          GLUCOSE_INSTALL_DIR=glucose-src/install \
          CADICAL_INSTALL_DIR=cadical-src/install \
          CMS_INSTALL_DIR=cms-src/install

      - name: Copy JNI libs to resources folder
        working-directory: jni
        run: make res

      - name: Download Cryptominisat
        run: |
          mkdir -p bin
          wget -qO- https://github.com/msoos/cryptominisat/releases/download/5.8.0/cryptominisat5_amd64_linux_static.gz | zcat > bin/cryptominisat5
          chmod +x bin/cryptominisat5
          echo "$(realpath bin)" >> $GITHUB_PATH

      - name: Run tests
        run: ./gradlew test --stacktrace

      - name: Upload to GH Releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            jni/build/lib/libjminisat.so
            jni/build/lib/libjglucose.so
            jni/build/lib/libjcadical.so
            jni/build/lib/libjcms.so
            jni/minisat-src/install/lib/libminisat.so
            jni/glucose-src/install/lib/libglucose.so
            jni/cadical-src/install/lib/libcadical.so
            jni/cms-src/install/lib/libcryptominisat5.so
