name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup build cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build package
        run: ./gradlew clean build -x test --stacktrace --scan

      - name: Download Cryptominisat
        run: |
          mkdir -p bin
          wget -qO- https://github.com/msoos/cryptominisat/releases/download/5.7.1/cryptominisat5-amd64-linux.gz | zcat > bin/cryptominisat5
          chmod +x bin/cryptominisat5
          echo "::add-path::$(realpath bin)"

      - name: Download kotlin-jnisat shared libs
        run: |
          ./gradlew downloadLibs
          sudo ldconfig $(realpath libs)

      - name: Run tests
        run: ./gradlew test --stacktrace
